### PR TITLE
fix(OSD-10205): add semver validation for policies

### PR DESCRIPTION
**Pull request by shibumi**
This adds semver validation as suggested by @georgettica and tracked by: [OSD-10205](https://issues.redhat.com/browse/OSD-10205)

### CODE REVIEW

**Comment by shibumi** [comment]
The tests are fun fine.. this might be further testing. Any advice how I can test this?

**Comment by fahlmant** [comment]
Can you show the output of using this command with at least one OCP version that doesn't conform to x.y.z?

**Comment by shibumi** [comment]
> Can you show the output of using this command with at least one OCP version that doesn't conform to x.y.z?

I will try. I never used osdctl to be honest...

**Comment by shibumi** [comment]
@fahlmant This throws an error:
```
❯ ./osdctl sts policy-diff 4.9.21 4.10.0-rc.8
exit status 1error: exit status 1
```

I will investigate

**Comment by fahlmant** [comment]
This has to do with your personal `oc` binary. What version do you have?

**Comment by shibumi** [comment]
@fahlmant 
```
❯ oc version
oc v3.11.0+20c5b86
kubernetes v1.10.0+b3b92b2
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

That's the one from the Fedora 35 repositories

**Comment by ravitri** [comment]
@shibumi - Can use https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.9.23.tar.gz and try again?

**Comment by shibumi** [comment]
@ravitri  my fault.. I had the right oc version in my $HOME/bin directory, but it gets called at the end of the $PATH, hence the Fedora 35 version got always executed.

The output is as follows:
```
❯ ./osdctl sts policy-diff 4.9.21 4.10.0-rc.8
Only in /tmp/crs-4.10.0-rc.8: 0000_30_capi-operator_00_credentials-request.yaml
Only in /tmp/crs-4.10.0-rc.8: 0000_50_cluster-network-operator_02-cncc-credentials.yaml
```

**Review by fahlmant — APPROVED** [review]
/approve

**Comment by ravitri** [comment]
Not sure my lgtm will work. Let's see.. 
/lgtm

**Pull request merged**
