### PR TITLE
Remove SL being sent when banned user is found

### PR DESCRIPTION
**Pull request by AlexVulaj**
As of [OCM-6631](https://issues.redhat.com/browse/OCM-6631) OCM is now responsible for sending this service log.

Resolves [OSD-21532](https://issues.redhat.com/browse/OSD-21532)

### CODE REVIEW

**Comment by AlexVulaj** [comment]
/hold

The OCM change is still waiting to go to production.

**Review by mjlshen — APPROVED** [review]
/lgtm

**Comment by AlexVulaj** [comment]
/unhold

the ocm change is now in prod

**Pull request merged**
