### PR TITLE
[OSD-12879] Fix assume role for rotate and generate secret

### PR DESCRIPTION
**Pull request by wshearn**
@fahlmant @iamkirkbater

### CODE REVIEW

**Comment by afreiberger** [comment]
Minor nit, the aws.Int64(900) variable in the calls is hard to understand w/out referencing documentation outside this codebase.  Any way we might be able to define an "aws token timeout" variable that equals aws.Int64(900) and reference that in the function calls to enhance readability and ensure that future update to one 900 second timeout addresses all token timeouts?

This was a pre-existing pattern, so I realize I'm asking for an enhancement during this functionality add.

**Comment by wshearn** [comment]
I think something like that would be better as an enhancement issue on here or jira. As you pointed out it is a preexisting pattern, so a card to make sure it is common across the entire codebase would be better.

**Comment by wshearn** [comment]
/hold

@fahlmant Looking at their request, it seems that aws.Int for this timeout is really only used in these two files, and will be low effort to change, the thing is the only other place it is used once is with aws.Int(0) for the timeout so not a full change everywhere which makes me not want to put it in the const file.
I am thinking maybe put it in the options struct of each file?

**Comment by fahlmant** [comment]
+1 to making that change

**Comment by clcollins** [comment]
@wshearn is this ready to go?  Anything related to @fahlmant's request holding this up?

**Pull request closed without merging**
