### PR TITLE
Updated struct data type while unmarshal clusterkubeconfig operation

### PR DESCRIPTION
**Pull request by shitaljante**
Related to - https://issues.redhat.com/browse/OSD-13939
 
Changes include:
1. Added "NewYAMLOrJSONDecoder" to use "json:" annotations while parsing yaml data. 
2. Marshal data to YAML while storing the local kubeconfig file.

Why: 
Currently client-go does not declare yaml go struct tags for the kubeconfig types(clientcmdapiv1.Config). 
In order to marshal the data object used a common method which supports both format yaml and json.

### CODE REVIEW

**Comment by mrbarge** [comment]
@shitaljante thanks for making this change. I was able to verify a populated kubeconfig for a private cluster so it functionally seems to be correct.

I think it is worth being clear in the PR description why this change is doing what it's doing, specifically declaring the types. From what I can see, this seems to be because the client-go does not declare yaml go struct tags for the kubeconfig types, is that correct?

I see that there is a way to successfully unmarshal the yaml regardless of the absent go struct tags by using `NewYAMLOrJSONDecoder` (from `k8s.io/apimachinery/pkg/util/yaml`), which would not require declaring a whole new type.

```
	formattedKubeconfig := clientcmdapiv1.Config{}
	d := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(data), len(data))
	if err := d.Decode(&formattedKubeconfig); err != nil {
             // handle error
	}
```

From there, it could potentially be marshalled back to yaml after first marshalling to json (so that the json go struct tags are respected) and then converting the json to yaml. 

I would really like to see that explored if possible, because it might be a lot cleaner. Would you mind having a look? Happy to help with this if needed so let me know.

Otherwise, if that isn't possible, may I suggest that the type declarations be moved outside of the `access.go` file and maybe migrated into the `k8s` package in `pkg/k8s` instead.

**Comment by shitaljante** [comment]
Thank you @mrbarge ! 
Updated changes as per suggestion,PTAL.

**Comment by mrbarge** [comment]
Fantastic, thank you @shitaljante , this makes it a lot nicer.
I gave it a quick test on a private cluster and it seemed to work well.

/lgtm

**Review by fahlmant — APPROVED** [review]
/approve
/lgtm

**Comment by shitaljante** [comment]
@fahlmant Can you please let me know if anything you are expecting here to unhold PR?

**Comment by fahlmant** [comment]
/hold cancel
Was just waiting for the change freeze so this didn't get accidentally merged before it was lifted

**Comment by shitaljante** [comment]
Thank You.
I really appreciate if I can get a lgtm label again.

**Pull request merged**
