### PR TITLE
[OSD-12879] Fix assume role for rotate and generate secret

### PR DESCRIPTION
**Pull request by wshearn**
I messed up and accidently closed #275 while trying to rebase and clean up
But this is all the requested changes from 275

### CODE REVIEW

**Review by fahlmant — COMMENTED** [review]
Generally looks good to me, has this been tested on a stage cluster?

**Comment by wshearn** [comment]
It has been tested on a stage cluster, I want to get more eyes on the PR and an approval before I run it against a prod cluster, making sure everything lines up and the SOP is fully updated.

**Pull request merged**
