### PR TITLE
OSD-13321 Bump dependencies and minimum golang version

### PR DESCRIPTION
**Pull request by mrbarge**
# What it does

This PR is a general maintenance/hygiene activity of `osdctl` to bump its package dependencies to more recent versions, specifically k8s, Hive, and some SRE operators. In doing so, it also bumps the minimum golang version to `1.17`.

# Context

[SDE-1972](https://issues.redhat.com//browse/SDE-1972) has aligned SRE operators to recent versions of k8s dependencies. This has also resulted in changes to the API package locations for several SRE operators, notably `aws-account-operator` and `gcp-project-operator`.

This change originally was intended to just bump AAO and GPO dependencies to make `osdctl` use the new API location, however, doing so also meant that several k8s dependencies required a similar bump. 

The process of doing this change also uncovered a few small already-existing issues in `osdctl`, which have been corrected in this PR. A full summary is below.

Refs [OSD-13321](https://issues.redhat.com//browse/OSD-13321) 

# Summary of changes

## `go.mod`

- `aws-account-operator` bumped to latest version
- `gcp-project-operator` bumped to latest version
- `hive` and `hive/apis` bumped to latest versions (`hive/apis` is pinned to a version in `replace` to allow `hive` to also import)
- `k8s.io` dependencies aligned to `0.24.3`
- `controller-runtime` bumped to `0.12.1`
 
## Import paths

Across the board, any usage of `aws-account-operator` and `gcp-project-operator`'s old API package locations have been revised to point to the new locations:

- `github.com/openshift/aws-account-operator/pkg/apis/aws/v1alpha1` => `github.com/openshift/aws-account-operator/api/v1alpha1`
- `github.com/openshift/gcp-project-operator/pkg/apis/gcp/v1alpha1` => `github.com/openshift/gcp-project-operator/api/v1alpha1`

## `osdctl clusterdeployment list`

- This command was found to be panicking in the existing release due to use of an uninitialized kube client. This bug has been corrected.
- Additionally, `hive` has long since removed the recording of `ClusterVersion` as part of a `ClusterDeployment` status, so the feature was never properly extracting this information to be able to display it. This code has been revised to pull the cluster's version from the `hive.openshift.io/version-major-minor-patch` label instead.

## `cmd/clusterdeployment/mock/k8s/client.go`

- mock generated to align with changes stemming from the k8s `controller-runtime` version bump.

## `pkg/k8s/client.go`

- updated to align with changes stemming from the k8s `controller-runtime` version bump.

## `pkg/k8s/account_test.go`

- some tests were updated to ensure that `ResourceVersion` was set in the "expected" object, as the updated k8s fakeclient now populates this field to a default when working with objects (previously it did not).

# Testing

This PR has been tested across numerous commands to verify they still operate successfully. Commands tested:

- `osdctl cluster context`
- `osdctl aao pool`
- `osdctl account console`
- `osdctl account cli`
- `osdctl clusterdeployment listresources` (for both AWS and GCP clusters)
- `osdctl clusterdeployment list`
- `osdctl completion`
- `osdctl network packet-capture`
- `osdctl servicelog post`
- `osdctl account mgmt list`
- `osdctl account list account`

### CODE REVIEW

**Review by fahlmant — APPROVED** [review]
/approve
/lgtm

**Comment by mrbarge** [comment]
Looks like this'll need a bump in the CI config to golang 1.17, at a best guess, in order to make the tests pass. [0]

I'll look into that, provided that there's no general objections to the PR in the meantime about the move to 1.17. 

[0] https://github.com/openshift/release/tree/master/ci-operator/config/openshift/osdctl

**Comment by mrbarge** [comment]
https://github.com/openshift/release/pull/32663 has been raised to bump the CI builder image to 1.17 (required to make these tests pass)

**Pull request merged**
