### PR TITLE
OSD-6004 - Add command to template and post ServiceLogs to OCM

### PR DESCRIPTION
**Pull request by drpaneas**
#### How to use:

1. Login to the correct environment using `ocm login`.
2. Create a template (e.g. see `./hack/example_template.json` as an example). In the template you can (but you are not forced to) create two placeholders `"${CLUSTER_UUID}"` and `${CASE_ID}"`. Instead of creating the template locally on your hard disk, you can also point to a template via a link/URL.
3. Run the command:

```bash
osdctl servicelog post -t ./hack/example_template.json -c "sdfsf-sfsdf-sfsfs-sdfsdf-sdf" -i "23442424"
```

_Notice_: In case you didn't use the placeholders in the template you can obviously omit the flags (`-c` or/and `-i`).

```bash
osdctl servicelog post -t ./hack/example_template.json
```

_Notice_:In any case, if you do any mistake with the parameters the message will not send and the command will fail with the appropriate message, suggesting you how to fix your error.

**WARNING: There's a bug!**:
>  I have noticed the OCM (or the API) has a bug: if you have logged into another environment (e.g. stage) but the cluster you want to send the message is at another environment (e.g. prod), then it sends the message successfully -- however the message IS NOT VISIBLE on the Web UI console. To make it visible to the Web UI console you have to to send the message being logged into the same environment the cluster belongs.

**Proposal to fix this**:
1. Open a bug and wait for someone to fix this properly.
2. In the meantime:
> Avoiding the issue with the bug: ask the user to give the cluster internal id instead of the external id. Then use the magic behind `ocm describe` to fetch the external id. If this succeeds, it means the user is logged in into the correct environment, otherwise it will fail without finding the cluster.

#### Room for improvement
* Add more tests. Since this is an urgent feature I wrote as many tests I could in the given time and I used the code from OCM `cmd/post` command -- which doesn't have any on their side anyways.
* More parameters can be added of course -- just let me know which you want :)

### CODE REVIEW

**Comment by drpaneas** [comment]
Importing `ocm` pkg creates a problem with the flag `v` being used twice. 

```
go build  -ldflags="-X 'github.com/openshift/osd-utils-cli/cmd.GitCommit=31022a3'" -o ./bin/osdctl main.go
./bin/osdctl docs ./docs/command
panic: unable to redefine 'v' shorthand in "cli" flagset: it's already used for "verbose" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000611300, 0xc000612be0)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x6f0
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc000612be0)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:887 +0xa8
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc000128300, 0xc0001437d8)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x94
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc000611300, 0xc000128300)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:885 +0x58
github.com/spf13/cobra.(*Command).mergePersistentFlags(0xc000623b80)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1612 +0x92
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0xc000623b80)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1004 +0x2f
github.com/spf13/cobra/doc.GenMarkdownCustom(0xc000623b80, 0x2bb79a0, 0xc0006161a0, 0x29f88c0, 0x0, 0x0)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/doc/md_docs.go:56 +0x56
github.com/spf13/cobra/doc.GenMarkdownTreeCustom(0xc000623b80, 0x7ffeefbfdd72, 0xe, 0x29f88c8, 0x29f88c0, 0x0, 0x0)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/doc/md_docs.go:155 +0x35f
github.com/spf13/cobra/doc.GenMarkdownTreeCustom(0xc00060f080, 0x7ffeefbfdd72, 0xe, 0x29f88c8, 0x29f88c0, 0x0, 0x0)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/doc/md_docs.go:139 +0x125
github.com/spf13/cobra/doc.GenMarkdownTreeCustom(0xc00060edc0, 0x7ffeefbfdd72, 0xe, 0x29f88c8, 0x29f88c0, 0x0, 0x0)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/doc/md_docs.go:139 +0x125
github.com/spf13/cobra/doc.GenMarkdownTree(0xc00060edc0, 0x7ffeefbfdd72, 0xe, 0xc0001b4200, 0x292062d)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/doc/md_docs.go:129 +0x57
github.com/openshift/osd-utils-cli/cmd.newCmdDocs.func1(0xc00062c000, 0xc000530650, 0x1, 0x1)
        /Users/drpaneas/gocode/src/github.com/openshift/osdctl/cmd/docs.go:24 +0x7e
github.com/spf13/cobra.(*Command).execute(0xc00062c000, 0xc000530620, 0x1, 0x1, 0xc00062c000, 0xc000530620)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00060edc0, 0xc000198000, 0x2bb79a0, 0xc000198008)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/drpaneas/gocode/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/drpaneas/gocode/src/github.com/openshift/osdctl/main.go:22 +0x153
make: *** [docs] Error 2
```

I couldn't resolve this in better way so I renamed our shorthand from `-v` to `-m`, while the `--verbose` remains as is. Another way is to not use `-v` shorthand at all (in case you don't like `-m`).

**Comment by drpaneas** [comment]
On a second thought using `-m` as a shorthand for `--verbose` feels ... awkward to say at least. So I decided to strip the shorthand completely out. Thus, if you want to use verbosity, you can type the full thing `--verbose`.

WDYT?

**Comment by mmazur** [comment]
lgtm

**Comment by drpaneas** [comment]
Since this is not reviewed yet, I completed the feature with parsing URL and added it as well :)

**Comment by 2uasimojo** [comment]
Just a drive-by comment:

I get notification emails for PRs like this, and I rely on the PR title to give me a clue as to what's going on. In this case it's just a Jira number. It would be neat if the title had some kind of description included.

Thanks!

**Comment by rogbas** [comment]
thanks @drpaneas, tested your version creating a couple of servicelogs in stage.


/approve
/lgtm

**Pull request merged**
