### PR TITLE
OSD-25695 - Remove Deprecated Cluster ID (-C) from Account Console Command

### PR DESCRIPTION
**Pull request by dustman9000**
Removes deprecated command and option from osdctl for accessing AWS accounts via Cluster ID. Backplane is now the preferred method of accessing accounts via Cluster ID.

[OSD-25695](https://issues.redhat.com//browse/OSD-25695)

### CODE REVIEW

**Comment by typeid** [comment]
@dustman9000 what stops us from using `osdctl account console -i <mc_aws_account_id> -p rhcontrol` to access MC consoles via `OrganizationAccessRole`? I have only ever used that, so lgtm.

/lgtm
/approve

**Review by typeid — APPROVED** [review]
/lgtm

**Comment by devppratik** [comment]
Removing the hold based on @typeid 's comment above

**Pull request merged**
